package com.udacity.gradle.jokeprovider;

public class JokeTeller {
    private String [] joke_list =
    {
        "I dreamt I was forced to eat a giant marshmallow. When I woke up, my pillow was gone.",
        "My dog used to chase people on a bike a lot. It got so bad, finally I had to take his bike away.",
        "When I see lovers\' names carved in a tree, I don\'t think it\'s sweet. I just think it\'s surprising how many people bring a knife on a date.",
        "I asked God for a bike, but I know God doesn\'t work that way. So I stole a bike and asked for forgiveness.",
        "Do not argue with an idiot. He will drag you down to his level and beat you with experience.",
        "I want to die peacefully in my sleep, like my grandfather.. Not screaming and yelling like the passengers in his car.",
        "Sex is not the answer. Sex is the question. \'Yes\' is the answer.",
        "The last thing I want to do is hurt you. But it\'s still on the list.",
        "Women might be able to fake orgasms. But men can fake a whole relationship.",
        "We live in a society where pizza gets to your house before the police.",
        "Light travels faster than sound. This is why some people appear bright until you hear them speak.",
        "If I agreed with you we\'d both be wrong.",
        "We never really grow up, we only learn how to act in public.",
        "Men have two emotions: Hungry and Horny. If you see him without an erection, make him a sandwich.",
        "Having sex is like playing bridge. If you don\'t have a good partner, you\'d better have a good hand.",
        "War does not determine who is right, only who is left.",
        "Knowledge is knowing a tomato is a fruit; Wisdom is not putting it in a fruit salad.",
        "Politicians and diapers have one thing in common. They should both be changed regularly, and for the same reason.",
        "Going to church doesn\'t make you a Christian any more than standing in a garage makes you a car.",
        "The early bird might get the worm, but the second mouse gets the cheese.",
        "Children: You spend the first 2 years of their life teaching them to walk and talk. Then you spend the next 16 years telling them to sit down and shut-up.",
        "My mother never saw the irony in calling me a son-of-a-bitch.",
        "Evening news is where they begin with ‘Good evening\', and then proceed to tell you why it isn\'t.",
        "If sex is a pain in the ass, then you\'re doing it wrong...",
        "A bus station is where a bus stops. A train station is where a train stops. On my desk, I have a work station..",
        "If you think nobody cares if you\'re alive, try missing a couple of payments.",
        "Better to remain silent and be thought a fool, than to speak and remove all doubt.",
        "If God is watching us, the least we can do is be entertaining.",
        "If 4 out of 5 people SUFFER from diarrhea... does that mean that one enjoys it?",
        "To steal ideas from one person is plagiarism. To steal from many is research.",
        "I thought I wanted a career, turns out I just wanted paychecks.",
        "Some people are like Slinkies ... not really good for anything, but you can\'t help smiling when you see one tumble down the stairs.",
        "Never, under any circumstances, take a sleeping pill and a laxative on the same night.",
        "How is it one careless match can start a forest fire, but it takes a whole box to start a campfire?",
        "Did you know that dolphins are so smart that within a few weeks of captivity, they can train people to stand on the very edge of the pool and throw them fish?",
        "I didn\'t fight my way to the top of the food chain to be a vegetarian",
        "A bank is a place that will lend you money, if you can prove that you don\'t need it.",
        "A computer once beat me at chess, but it was no match for me at kick boxing.",
        "I saw a woman wearing a sweat shirt with \'Guess\' on it...so I said \'Implants?\'",
        "Why does someone believe you when you say there are four billion stars, but check when you say the paint is wet?",
        "Women will never be equal to men until they can walk down the street with a bald head and a beer gut, and still think they are sexy.",
        "Whenever I fill out an application, in the part that says \'If an emergency, notify:\' I put \'DOCTOR\'. What\'s my mother going to do?",
        "A clear conscience is usually the sign of a bad memory.",
        "The shinbone is a device for finding furniture in a dark room.",
        "I didn\'t say it was your fault, I said I was blaming you.",
        "Good girls are bad girls that never get caught.",
        "God must love stupid people. He made SO many.",
        "The voices in my head may not be real, but they have some good ideas!",
        "Laugh at your problems, everybody else does.",
        "Artificial intelligence is no match for natural stupidity.",
        "Crowded elevators smell different to midgets.",
        "Fighting for peace is like fucking for virginity.",
        "Behind every successful man is his woman. Behind the fall of a successful man is usually another woman.",
        "The main reason Santa is so jolly is because he knows where all the bad girls live.",
        "The sole purpose of a child\'s middle name, is so he can tell when he\'s really in trouble.",
        "Always borrow money from a pessimist. He won\'t expect it back.",
        "He who smiles in a crisis has found someone to blame.",
        "You do not need a parachute to skydive. You only need a parachute to skydive twice.",
        "Never get into fights with ugly people, they have nothing to lose.",
        "It\'s not the fall that kills you; it\'s the sudden stop at the end.",
        "Some people say \'If you can\'t beat them, join them\'. I say \'If you can\'t beat them, beat them\', because they will be expecting you to join them, so you will have the element of surprise.",
        "Why do Americans choose from just two people to run for president and 50 for Miss America?",
        "Never hit a man with glasses. Hit him with a baseball bat.",
        "My opinions may have changed, but not the fact that I am right.",
        "We have enough gun control. What we need is idiot control.",
        "I intend to live forever. So far, so good.",
        "Some cause happiness wherever they go. Others whenever they go.",
        "A diplomat is someone who can tell you to go to hell in such a way that you will look forward to the trip.",
        "My psychiatrist told me I was crazy and I said I want a second opinion. He said okay, you\'re ugly too.",
        "Hospitality: making your guests feel like they\'re at home, even if you wish they were.",
        "Money can\'t buy happiness, but it sure makes misery easier to live with.",
        "I discovered I scream the same way whether I\'m about to be devoured by a great white shark or if a piece of seaweed touches my foot.",
        "I don\'t trust anything that bleeds for five days and doesn\'t die.",
        "I should\'ve known it wasn\'t going to work out between my ex-wife and me. After all, I\'m a Libra and she\'s a bitch.",
        "I got in a fight one time with a really big guy, and he said, \'I\'m going to mop the floor with your face.\' I said, \'You\'ll be sorry.\' He said, \'Oh, yeah? Why?\' I said, \'Well, you won\'t be able to get into the corners very well.\'",
        "Worrying works! 90% of the things I worry about never happen.",
        "When in doubt, mumble.",
        "I always take life with a grain of salt, ...plus a slice of lemon, ...and a shot of tequila.",
        "There\'s a fine line between cuddling and holding someone down so they can\'t get away.",
        "A little boy asked his father, \'Daddy, how much does it cost to get married?\' Father replied, \'I don\'t know son, I\'m still paying.\'",
        "Just remember...if the world didn\'t suck, we\'d all fall off.",
        "I used to be indecisive. Now I\'m not sure.",
        "You\'re never too old to learn something stupid.",
        "Women may not hit harder, but they hit lower.",
        "A bargain is something you don\'t need at a price you can\'t resist.",
        "Jesus loves you, but everyone else thinks you\'re an asshole.",
        "With sufficient thrust, pigs fly just fine.",
        "Knowledge is power, and power corrupts. So study hard and be evil.",
        "Nostalgia isn\'t what it used to be.",
        "When tempted to fight fire with fire, remember that the Fire Department usually uses water.",
        "To be sure of hitting the target, shoot first and call whatever you hit the target.",
        "You are such a good friend that if we were on a sinking ship together and there was only one life jacket... I\'d miss you heaps and think of you often.",
        "I like work. It fascinates me. I sit and look at it for hours.",
        "A TV can insult your intelligence, but nothing rubs it in like a computer.",
        "Hallmark Card: \'I\'m so miserable without you, it\'s almost like you\'re still here.\'",
        "If at first you don\'t succeed, skydiving is not for you!",
        "A bus is a vehicle that runs twice as fast when you are after it as when you are in it.",
        "Some people hear voices.. Some see invisible people.. Others have no imagination whatsoever.",
        "Virginity is like a soapbubble, one prick and it is gone.",
        "If winning isn\'t everything why do they keep score?",
        "Whoever coined the phrase \'Quiet as a mouse\' has never stepped on one.",
        "If you are supposed to learn from your mistakes, why do some people have more than one child.",
        "Change is inevitable, except from a vending machine.",
        "Don\'t miss: A Google Street View Murder Prank",
        "Why is it that most nudists are people you don\'t want to see naked?",
        "I don\'t suffer from insanity. I enjoy every minute of it.",
        "When you go into court, you are putting your fate into the hands of people who weren\'t smart enough to get out of jury duty.",
        "If you keep your feet firmly on the ground, you\'ll have trouble putting on your pants.",
        "What\'s the difference between a northern fairytale and a southern fairytale? A northern fairytale begins \'Once upon a time...\' A southern fairytale begins \'Y\'all ain\'t gonna believe this shit...\'",
        "Does this rag smell like chloroform to you?"
    };

    public String tellJoke(){
        return joke_list[(int) Math.floor(Math.random() * joke_list.length)];
    }

}
